apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: templated
  namespace: app
spec:
  path: kvv2/templated
  type: Opaque
  templates:
    foo: "{% .Secrets.foo %}"
    addr: "{% .Vault.Address %}"
